modLoader="javafml" #mandatory

loaderVersion="[47,)"

license="${mod_license}"
[[mods]] #mandatory
modId="${mod_id}" #mandatory

version="${mod_version}" #mandatory

displayName="${mod_name}" #mandatory

logoFile="wuxiacraft.png" #optional

credits="Thanks to everyone for liking and supporting this mod specially the official wuxiacraft discord server." #optional

authors="${mod_authors}" #optional

description='''
This is a mod that aims to make you into a main character of a wuxia novel, adding cultivation and auxiliary systems to make you feel like you're inside a complete magic wuxia like world.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.wuxiacraft]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[47,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.wuxiacraft]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
